### ISSUE TITLE
Banjo Kazooie

### ISSUE THREAD

**Issue by SpiceyWolf** [Isotarge/ScriptHawk#8]
Sorry, this isnt much of an 'issue' but I wanted to open a discussion. I come from the Ocarina Of Time Online development team. We have been expanding our work to be more game agnostic and Banjo Kazooie Online was a project that I am leading. I wanted to ask about how some of the data was collected here like is it just being collected from random online resources or if people are actually collecting it themselves for this repo... and if the latter is true someone here could help me find some info to help the development of BKO. I can be contacted through this post (obviously) or you can email me via spiceywolf.archaicsoft@outlook.com. Thank you for taking the time to read this and I understand if there isnt any interest in assisting me.

**Comment by MittenzHugg** [comment]
Collaboration being handled in private.
